logoutput: stderr
internal: 0.0.0.0 port = 1056
external: 127.0.0.1

clientmethod: none
socksmethod: username
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    socksmethod: username
}

# 关键：把认证后的流量转发给 tailscale 的上游 SOCKS5
route {
    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 1055
    proxyprotocol: socks_v5
}
